services:
  - type: web
    name: medical-report-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
    healthCheckPath: /
    autoDeploy: true 