services:
  - type: web
    name: medical-report-extractor
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-eng \
        libtesseract-dev \
        libleptonica-dev \
        pkg-config \
        build-essential \
        autoconf \
        automake \
        libtool \
        pkg-config \
        libpng-dev \
        libjpeg-dev \
        libtiff-dev \
        zlib1g-dev
      
      # Install Tesseract from source
      cd /tmp && \
      wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/4.1.1.tar.gz && \
      tar xvf 4.1.1.tar.gz && \
      cd tesseract-4.1.1 && \
      ./autogen.sh && \
      ./configure && \
      make && \
      make install && \
      ldconfig
      
      # Install language data
      cd /tmp && \
      wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata && \
      mkdir -p /usr/local/share/tessdata && \
      mv eng.traineddata /usr/local/share/tessdata/
      
      # Set environment variables
      export TESSDATA_PREFIX=/usr/local/share/tessdata
      export PATH=$PATH:/usr/local/bin
      
      # Verify installation
      which tesseract
      tesseract --version
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: |
      export TESSDATA_PREFIX=/usr/local/share/tessdata
      export PATH=$PATH:/usr/local/bin
      gunicorn app:app --timeout 300 --workers 1 --threads 1 --worker-class gthread --max-requests 1 --max-requests-jitter 1 --log-level debug --preload --worker-tmp-dir /dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        fromService: openai-api-key
      - key: FLASK_ENV
        value: production
      - key: MAX_CONTENT_LENGTH
        value: 16777216  # 16MB max file size
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: ALLOWED_EXTENSIONS
        value: pdf
      - key: MAPPING_FILE
        value: data/true_data.csv
      - key: TESSDATA_PREFIX
        value: /usr/local/share/tessdata
      - key: PATH
        value: $PATH:/usr/local/bin
    plan: free
    healthCheckPath: /health
    autoDeploy: true 